version: '3.1'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080

  ui:
    build:
      context: ../../ui
      dockerfile: Dockerfile
    ports:
      - 8082:5000
    depends_on:
       - api